# API Configuration для OpenRouter
openrouter:
  api_key: "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"
  base_url: "https://openrouter.ai/api/v1"
  model: "deepseek/deepseek-r1-0528:free"
  temperature: 0.7

# Embeddings Configuration
embeddings:
  model_name: "sentence-transformers/all-mpnet-base-v2"
  device: "cpu"

# Document Processing
document_processing:
  chunk_size: 1000
  chunk_overlap: 200
  supported_extensions: [".pdf", ".docx"]

# Vector Store
vector_store:
  index_name: "sales_assistant"
  persist_directory: "./data/vector_store"

# Assistant Configuration
assistant:
  max_context_length: 10
  session_timeout_hours: 24
  max_response_tokens: 1000
  language: "russian"

# Web Interface
web:
  host: "0.0.0.0"
  port: 8501
  title: "LAI - ИИ-ассистент для сотрудников"

