# API Configuration для OpenRouter
openrouter:
  api_key: "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"
  base_url: "https://openrouter.ai/api/v1"
  model: "deepseek/deepseek-r1-0528:free"
  temperature: 0.7

# Embeddings Configuration
embeddings:
  model_name: "sentence-transformers/all-mpnet-base-v2"
  device: "cpu"

# Document Processing
document_processing:
  chunk_size: 1000
  chunk_overlap: 200
  supported_extensions: [".pdf", ".docx"]

# Vector Store
vector_store:
  index_name: "sales_assistant"
  persist_directory: "./data/vector_store"

# Assistant Configuration
assistant:
  max_context_length: 10
  session_timeout_hours: 24
  max_response_tokens: 2000
  language: "russian"

# Web Interface
web:
  host: "0.0.0.0"
  port: 8501
  title: "LAI - ИИ-ассистент для сотрудников"
